"""initial

Revision ID: 24ea45b607ac
Revises: 
Create Date: 2025-06-10 22:08:17.900952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '24ea45b607ac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('chat_id', sa.BigInteger(), nullable=True),
                    sa.Column('fullname', sa.String(length=50), nullable=False),
                    sa.Column('phone', sa.String(length=12), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('chat_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
