"""initial

Revision ID: ac732a4d977a
Revises: 
Create Date: 2025-06-19 19:26:34.792535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'ac732a4d977a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.JSON(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('users',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('chat_id', sa.BigInteger(), nullable=True),
                    sa.Column('fullname', sa.String(length=50), nullable=False),
                    sa.Column('phone', sa.String(length=12), nullable=True),
                    sa.Column('lang', sa.String(length=2), server_default='uz', nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('chat_id')
                    )
    op.create_table('subcategory',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('category_id', sa.Integer(), nullable=True),
                    sa.Column('name', sa.JSON(), nullable=False),
                    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='cascade'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('quiz',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('text', sa.JSON(), nullable=False),
                    sa.Column('subcategory_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['subcategory_id'], ['subcategory.id'], ondelete='cascade'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('option',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('text', sa.JSON(), nullable=False),
                    sa.Column('quiz_id', sa.Integer(), nullable=True),
                    sa.Column('is_correct', sa.Boolean(), nullable=True),
                    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ondelete='cascade'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user_answer',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('quiz_id', sa.Integer(), nullable=True),
                    sa.Column('option_id', sa.Integer(), nullable=True),
                    sa.Column('answered_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['option_id'], ['option.id'], ),
                    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ondelete='cascade'),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='cascade'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_answer')
    op.drop_table('option')
    op.drop_table('quiz')
    op.drop_table('subcategory')
    op.drop_table('users')
    op.drop_table('category')
    # ### end Alembic commands ###
